project:
  type: book


website:
  favicon: images/logoUP.png

book:
  title: "Recueil Questions Entretien Quant"
  author: "Samy Mekkaoui"
  date: today
  repo-url: "https://github.com/SamyMekk/Exos_Entretien_Quant"
  chapters:
     - index.qmd
     - TesTSG.qmd
     - banques.qmd
     - Fonds.qmd
     - Conseil.qmd
     - Vrac.qmd
     - summary.qmd
     - references.qmd
    
  sidebar:
    style: docked
    logo: "images/logoUP.png"

format:
  html:
    mainfont: "Computer Modern Serif"
    theme:
      light: simplex
      dark: solar

bibliography: references.bib


